version: "3.8"
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:alpine
    container_name: database_${DATABASE}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres:
